services:

  db:
    container_name: mssql2019
    hostname: mssql2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_PID=Express
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -N -C -S localhost -U sa -P "${MSSQL_PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/db/data:/var/opt/mssql/data
      - ./.containers/db/log:/var/opt/mssql/log

  db-migrations:
    container_name: db-migrations
    hostname: db-migrations
    build:
      context: .
      dockerfile: src/Migrations/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - MSSQL_CONNECTION_STRING=${MSSQL_CONNECTION_STRING}

  api:
    build:
      context: .
      dockerfile: src/API/Dockerfile
    container_name: country-holiday-checker
    hostname: countryholidaychecker
    ports:
      - "8080:${ASPNETCORE_HTTP_CONTAINER_PORT}"
      - "8081:${ASPNETCORE_HTTPS_CONTAINER_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
    volumes:
      - .\certificates\https:/https:ro
    depends_on:
      db-migrations:
        condition: service_completed_successfully